services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq}
      RABBITMQ_DEFAULT_VHOST: '/'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
  redis:
    image: redis/redis-stack-server:7.2.0-v10
    restart: unless-stopped
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD:-lnasdoifna0asd}'
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    volumes:
      - redis_data:/data
  vosk-server:
    image: alphacep/kaldi-grpc-en:latest
    restart: unless-stopped
    expose:
      - '5001'
  vosk-proxy:
    build:
      context: ../jambonz-vosk-proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VOSK_URL: 'vosk-server:5001'
      HTTP_PORT: 3008
      API_KEY: 'testapikey'
      LOGLEVEL: 'debug'
    ports:
      - '3008:3008'
  ivr-app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    environment:
      - LOKI_ENABLED=false
    ports:
      - '${HTTP_PORT:-8080}:${HTTP_PORT:-8080}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${HTTP_PORT}/api/v1/health']
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 3s
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data: {}
  redis_data: {}
