services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq}
      RABBITMQ_DEFAULT_VHOST: '/'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
  vosk-server:
    image: alphacep/kaldi-grpc-en:latest
    restart: unless-stopped
    expose:
      - '5001'
  vosk-proxy:
    image: sptmru/vosk-proxy:latest
    restart: unless-stopped
    environment:
      VOSK_URL: 'vosk-server:5001'
      HTTP_PORT: 3008
      API_KEY: 'testapikey'
      LOGLEVEL: 'debug'
    ports:
      - '3008:3008'
  ivr-app:
    image: sptmru/jambonz-ivr-app:0.55
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    environment:
      LOKI_ENABLED: ${LOKI_ENABLED}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_TO_FILE: ${LOG_TO_FILE}
      HTTP_PORT: ${HTTP_PORT}
      WS_ENABLED: ${WS_ENABLED}
      JAMBONZ_ACCOUNT_SID: ${JAMBONZ_ACCOUNT_SID}
      JAMBONZ_APPLICATION_SID: ${JAMBONZ_APPLICATION_SID}
      JAMBONZ_API_KEY: ${JAMBONZ_API_KEY}
      JAMBONZ_BASE_URL: ${JAMBONZ_BASE_URL}
      JAMBONZ_CALLBACK_BASE_URL: ${JAMBONZ_CALLBACK_BASE_URL}
      JAMBONZ_SIP_REALM: ${JAMBONZ_SIP_REALM}
    ports:
      - '${HTTP_PORT:-8080}:${HTTP_PORT:-8080}'
      - '${WS_PORT:-8081}:${WS_PORT:-8081}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${HTTP_PORT}/api/v1/health']
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 3s
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: {}
