version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
  redis:
    image: redis/redis-stack-server:7.2.0-v10
    environment:
      REDIS_ARGS: '--requirepass lnasdoifna0asd'
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data: {}
  redis_data: {}
