export const CallDetailsDefinition = {
  $id: 'CallDetails',
  type: 'object',
  required: [
    'numberTo',
    'numberFrom',
    'wavUrlAnnounce',
    'wavUrlContinue',
    'wavUrlOptOut',
    'wavUrlVM',
    'transactionId',
    'carrierAddress',
    'destinationAddress',
    'digitContinue',
    'digitOptOut',
  ],
  properties: {
    numberTo: { type: 'string' },
    numberFrom: { type: 'string' },
    wavUrlAnnounce: { type: 'string' },
    wavUrlContinue: { type: 'string' },
    wavUrlOptOut: { type: 'string' },
    wavUrlVM: { type: 'string' },
    transactionId: { type: 'string' },
    carrierAddress: { type: 'string' },
    destinationAddress: { type: 'string' },
    digitContinue: { type: 'string' },
    digitOptOut: { type: 'string' },
  },
};
